export const FETCH_HABITS = 'FETCH_HABITS';
export const CREATE_HABIT = 'CREATE_HABIT';
export const FETCH_HABIT = 'FETCH_HABIT';
export const UPDATE_HABIT = 'UPDATE_HABIT';
export const DELETE_HABIT = 'DELETE_HABIT';

export const CREATE_DATAPOINT = 'CREATE_DATAPOINT';
export const UPDATE_DATAPOINT = 'UPDATE_DATAPOINT';
export const DELETE_DATAPOINT = 'DELETE_DATAPOINT';
